### ISSUE TITLE
[BUG] Generated Factory class for tables with ForeignId columns have incorrect data type

### ISSUE THREAD

**Issue by deanlj** [TiagoSilvaPereira/vemto-issues#127]
**Describe the bug**
The generated factory for a table with ForeignId columns uses $this->faker->word instead of an unsigned big integer

**To Reproduce**
1. Create a new model in the schema editor
2. add some columns of type foreign id
3. generate the app
4. the generated factory uses $this->faker->word when it should be an integer value

**Expected behavior**
The generated factory should use unsigned integer values instead of strings

**Screenshots**
Migration:
        Schema::create('workflow_conditions', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('description')->nullable();
            $table->foreignId('data_object_id');
            $table->foreignId('data_object_attribute_id');
            $table->text('validation');

            $table->timestamps();
        });
        
Factory:
    public function definition()
    {
        return [
            'name' => $this->faker->name,
            'description' => $this->faker->text(255),
            **'data_object_id' => $this->faker->word,**
            **'data_object_attribute_id' => $this->faker->word,**
            'validation' => $this->faker->text,
        ];
    }

**Desktop (please complete the following information):**
 - OS: MacOs Mojave

**Comment by TiagoSilvaPereira** [comment]
Fixed on the version 0.9.2

**Comment by deanlj** [comment]
Hi Tiago

I've just re-generated my app with v0.9.2 and the problem is still there

To reproduce

add a column called current_payer_id to the user model with a type of ForeignID

There is no relationship, just a column as the id will be a foreign key in to a table created by a package

Generate the app

the User factory looks like

```php
    public function definition()
    {
        return [
            'name' => $this->faker->name,
            'email' => $this->faker->email,
            'email_verified_at' => now(),
            'password' => \Hash::make('password'),
            'remember_token' => Str::random(10),
            'current_payer_id' => $this->faker->word,
        ];
    }
```

The current_payer_id should be an unsigned big int

**Comment by TiagoSilvaPereira** [comment]
Hi @deanlj if it is an old project, please change the faker on Field Options. The fix is for new projects
![image](https://user-images.githubusercontent.com/11933789/118364489-fcf6e100-b56e-11eb-97b1-c5edded8c548.png)

**Comment by TiagoSilvaPereira** [comment]
Hi @deanlj for old projects, please change the faker on the field options. It was fixed for new projects:
![image](https://user-images.githubusercontent.com/11933789/118364606-7abaec80-b56f-11eb-900b-2eadddd6e562.png)

**Comment by deanlj** [comment]
awesome, thank you.
